<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <SkiaSharpVersion>4.151.2</SkiaSharpVersion>
    <SDL3Version>3.4.16</SDL3Version>
    <SDL3MixerVersion>3.2.4.11</SDL3MixerVersion>
    <MELVersion>10.0.11</MELVersion>
  </PropertyGroup>

  <!-- Game -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MELVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="$(MELVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="$(MELVersion)" />
    <PackageVersion Include="NReco.Logging.File" Version="1.4.0" />
    <PackageVersion Include="FFmpeg.AutoGen" Version="9.0.1.1" />
    <PackageVersion Include="SkiaSharp" Version="$(SkiaSharpVersion)" />
    <PackageVersion Include="SkiaSharp.NativeAssets.WebAssembly" Version="$(SkiaSharpVersion)" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Win32" Version="$(SkiaSharpVersion)" />
    <PackageVersion Include="SkiaSharp.NativeAssets.macOS" Version="$(SkiaSharpVersion)" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="$(SkiaSharpVersion)" />
    <PackageVersion Include="SDL3-CS" Version="$(SDL3Version)" />
    <PackageVersion Include="SDL3-CS.Windows" Version="$(SDL3Version)" />
    <PackageVersion Include="SDL3-CS.Linux" Version="$(SDL3Version)" />
    <PackageVersion Include="SDL3-CS.MacOS" Version="$(SDL3Version)" />
    <PackageVersion Include="SDL3-CS.Windows.Mixer" Version="$(SDL3MixerVersion)" />
    <PackageVersion Include="SDL3-CS.Linux.Mixer" Version="$(SDL3MixerVersion)" />
    <PackageVersion Include="SDL3-CS.MacOS.Mixer" Version="$(SDL3MixerVersion)" />
  </ItemGroup>


  <!-- Tests -->
  <ItemGroup>
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>

</Project>
