<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <MonoGameVersion>3.8.5.1</MonoGameVersion>
  </PropertyGroup>

  <!-- Game -->
  <ItemGroup>
    <PackageVersion Include="FontStashSharp.MonoGame" Version="1.5.8" />
    <PackageVersion Include="Microsoft.NETCore.Jit" Version="1.0.12" />
    <PackageVersion Include="MonoGame.Framework.Native" Version="$(MonoGameVersion)" />
    <PackageVersion Include="MonoGame.Framework.DesktopGL" Version="$(MonoGameVersion)" />
    <PackageVersion Include="MonoGame.Runtime.Windows.Vulkan" Version="$(MonoGameVersion)" />
    <PackageVersion Include="MonoGame.Runtime.Mac.Vulkan" Version="$(MonoGameVersion)" />
    <PackageVersion Include="MonoGame.Runtime.Linux.Vulkan" Version="$(MonoGameVersion)" />
    <PackageVersion Include="FFmpeg.AutoGen" Version="8.1.0" />
    <PackageVersion Include="SkiaSharp" Version="4.151.2" />
    <PackageVersion Include="SkiaSharp.NativeAssets.WebAssembly" Version="4.151.2" />
  </ItemGroup>

  <!-- Content builder -->
  <ItemGroup>
    <PackageVersion Include="MonoGame.Framework.Content.Pipeline" Version="$(MonoGameVersion)" />
    <PackageVersion Include="MonoGame.Tool.Basisu" Version="2.0.2.1" />
    <PackageVersion Include="MonoGame.Tool.Crunch" Version="1.0.4.7" />
    <PackageVersion Include="MonoGame.Tool.Dxc" Version="1.8.2505.11" />
    <PackageVersion Include="MonoGame.Tool.FFmpeg" Version="7.0.0.10" />
    <PackageVersion Include="MonoGame.Tool.FFprobe" Version="7.0.0.10" />
  </ItemGroup>

  <!-- Tests -->
  <ItemGroup>
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>

</Project>
