<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CutTheRopeDX</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="CutTheRope-DX" />
    <InternalsVisibleTo Include="CutTheRopeDX.Tests" />
    <InternalsVisibleTo Include="CutTheRopeDX.Desktop.Tests" />
    <InternalsVisibleTo Include="CutTheRopeDX.Browser" />
    <InternalsVisibleTo Include="CutTheRopeDX.Rendering.Skia" />
    <InternalsVisibleTo Include="CutTheRopeDX.Rendering.Skia.Tests" />
    <InternalsVisibleTo Include="CutTheRopeDX.Desktop.Platform" />
    <InternalsVisibleTo Include="CutTheRopeDX.Desktop.Platform.Tests" />
  </ItemGroup>
</Project>
