namespace CutTheRope.game
{
    public enum UNLOCKEDSTATE
    {
        UNLOCKEDSTATELOCKED,
        UNLOCKEDSTATEUNLOCKED,
        UNLOCKEDSTATEJUSTUNLOCKED,
        UNLOCKEDSTATEJUSTUNLOCKEDWITHCHEAT
    }
}
