#!/usr/bin/env python3
"""Regenerates EasterEggOmNomArt.cs from the web edition's canvas drawing code.

Usage: gen-omnom-vector.py <path to cuttherope-h5dx checkout>

The source draws Om Nom as six flat-filled paths of Canvas2D commands. This lifts those
commands verbatim into C# path data; the fill colors and the draw order come across with
them. Nothing here interprets the geometry -- flattening and tessellation happen at run time.
"""
import re
import sys
from pathlib import Path

LAYERS = ["dark", "light", "outline", "white", "leftPupil", "rightPupil"]

# Command counts and fill colors as they stand in the source. A mismatch means the source
# changed shape and the output needs review rather than a silent regeneration.
EXPECTED = {
    "dark": (7, 107, (100, 150, 40)),
    "light": (4, 163, (153, 205, 0)),
    "outline": (9, 413, (35, 44, 30)),
    "white": (5, 105, (255, 255, 255)),
    "leftPupil": (1, 11, (0, 0, 0)),
    "rightPupil": (1, 13, (0, 0, 0)),
}

TOKEN = re.compile(
    r'ctx\.(moveTo|lineTo|bezierCurveTo|closePath|beginPath|fillStyle)\s*'
    r'(?:\(([^)]*)\)|=\s*"rgb\(([^)]*)\)")')


def parse(source):
    layers = []
    current = None
    for match in TOKEN.finditer(source):
        op, args, rgb = match.group(1), match.group(2), match.group(3)
        if op == "beginPath":
            current = {"commands": [], "subpaths": 0, "fill": None}
            layers.append(current)
        elif current is None:
            continue
        elif op == "fillStyle":
            current["fill"] = tuple(int(v.strip()) for v in rgb.split(","))
        elif op == "closePath":
            current["commands"].append(("Z", []))
        else:
            nums = [float(v) for v in re.findall(r"-?\d+\.?\d*", args)]
            if op == "moveTo":
                current["subpaths"] += 1
                current["commands"].append(("M", nums))
            elif op == "lineTo":
                current["commands"].append(("L", nums))
            else:
                current["commands"].append(("C", nums))
    return layers


def verify(layers):
    if len(layers) != len(LAYERS):
        sys.exit(f"expected {len(LAYERS)} paths, found {len(layers)}")
    for name, layer in zip(LAYERS, layers):
        subpaths, commands, fill = EXPECTED[name]
        drawn = [c for c in layer["commands"] if c[0] != "Z"]
        if layer["subpaths"] != subpaths:
            sys.exit(f"{name}: expected {subpaths} subpaths, found {layer['subpaths']}")
        if len(drawn) != commands:
            sys.exit(f"{name}: expected {commands} commands, found {len(drawn)}")
        if layer["fill"] != fill:
            sys.exit(f"{name}: expected fill {fill}, found {layer['fill']}")


def emit(layers):
    out = [
        "using CutTheRopeDX.Framework;",
        "using CutTheRopeDX.Framework.Visual;",
        "",
        "namespace CutTheRopeDX.GameMain",
        "{",
        "    /// <summary>",
        "    /// Om Nom drawn as filled vector paths, in the order the layers stack: the shaded",
        "    /// green body, its lighter face, the dark outline, the eye whites, then each pupil.",
        "    /// Generated by <c>scripts/gen-omnom-vector.py</c>; edit that, not this.",
        "    /// </summary>",
        "    internal static class EasterEggOmNomArt",
        "    {",
        "        /// <summary>One filled path and the color it is filled with.</summary>",
        "        /// <param name=\"Commands\">The path's drawing operations.</param>",
        "        /// <param name=\"Fill\">The color the path is filled with.</param>",
        "        internal readonly record struct Layer(VectorPathCommand[] Commands, RGBAColor Fill);",
        "",
        "        private static VectorPathCommand M(float x, float y)",
        "        {",
        "            return new(VectorPathVerb.MoveTo, x, y, 0f, 0f, 0f, 0f);",
        "        }",
        "",
        "        private static VectorPathCommand L(float x, float y)",
        "        {",
        "            return new(VectorPathVerb.LineTo, x, y, 0f, 0f, 0f, 0f);",
        "        }",
        "",
        "        private static VectorPathCommand C(",
        "            float x0, float y0, float x1, float y1, float x2, float y2)",
        "        {",
        "            return new(VectorPathVerb.CubicTo, x0, y0, x1, y1, x2, y2);",
        "        }",
        "",
        "        private static VectorPathCommand Z()",
        "        {",
        "            return new(VectorPathVerb.Close, 0f, 0f, 0f, 0f, 0f, 0f);",
        "        }",
        "",
    ]
    names = []
    for name, layer in zip(LAYERS, layers):
        field = name[0].upper() + name[1:]
        names.append(field)
        out.append(f"        private static readonly VectorPathCommand[] {field} =")
        out.append("        [")
        for op, nums in layer["commands"]:
            args = ", ".join(f"{v:g}f" for v in nums)
            out.append(f"            {op}({args}),")
        out.append("        ];")
        out.append("")
    out.append("        /// <summary>The layers, in draw order.</summary>")
    out.append("        public static readonly Layer[] Layers =")
    out.append("        [")
    for name, layer in zip(LAYERS, layers):
        field = name[0].upper() + name[1:]
        r, g, b = layer["fill"]
        out.append(
            f"            new({field}, RGBAColor.MakeRGBA("
            f"{r}f / 255f, {g}f / 255f, {b}f / 255f, 1f)),")
    out.append("        ];")
    out.append("    }")
    out.append("}")
    return "\n".join(out) + "\n"


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    source = (Path(sys.argv[1]) / "src/ui/EasterEggOmNom.ts").read_text()
    layers = parse(source)
    verify(layers)
    target = Path(__file__).resolve().parent.parent / (
        "src/CutTheRopeDX.Core/GameMain/EasterEggOmNomArt.cs")
    target.write_text(emit(layers))
    total = sum(len([c for c in l["commands"] if c[0] != "Z"]) for l in layers)
    print(f"wrote {target} ({total} commands across {len(layers)} layers)")


if __name__ == "__main__":
    main()
